-- ProjNav VHDL simulation template: TB_SISTEMA_COMPLETO.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
